### ISSUE TITLE
Не запускается SUT db-api.jar

### ISSUE THREAD

**Issue by MironovED** [MironovED/3.1_Docker#1]
**Шаги воспроизведения**
1. Создать папку на локальной компьютере
2. Добавить в папку SUT db-api.jar
3. Добавить в папку файл docker-compose.yml
4. Добавить в папку файл application.properties
5. Вызвать терминал по адресу папки 
6. Ввести команду docker-compose up
7. Ввести команду java -jar db-api.jar

**Фактический результат**
![Снимок экрана 2022-04-10 в 23 08 30](https://user-images.githubusercontent.com/95146207/162637892-be115257-c2e7-4a83-9be3-97d2d7946c4a.png)
![Снимок экрана 2022-04-10 в 23 08 37](https://user-images.githubusercontent.com/95146207/162637898-1147635d-7176-4274-9355-93acbb6d192d.png)

Окружение
Safari Версия 15.3 (16612.4.9.1.8, 16612)
Google Chrome Версия 100.0.4896.75 (Официальная сборка), (x86_64)
macOS Big Sur ver. 11.6.4
IntelliJ IDEA 2021.3 (Community Edition)

**Comment by andrew-pahomov** [comment]
Было бы интересно посмотреть также логи запуска контейнера. Основная ошибка это проброс неверного порта. PostgreSQL работает на порту 5432, его и надо было пробрасывать.

**Comment by MironovED** [comment]
Исправил порт на 5432

Логи контейнера
![Логи контейнера](https://user-images.githubusercontent.com/95146207/163043389-6ebd7a91-ff77-42a2-9d10-ffe07b3f6743.png)

Логи приложения
![Снимок экрана 2022-04-12 в 22 56 04](https://user-images.githubusercontent.com/95146207/163043491-70866de4-33a4-49d3-92e4-e0121e41b8df.png)
![Снимок экрана 2022-04-12 в 22 56 39](https://user-images.githubusercontent.com/95146207/163043500-d10b34d2-ea6b-4d59-9566-4043774bfb9d.png)

**Comment by andrew-pahomov** [comment]
Имя базы данных и учетные данные в файле docker-compose.yml должны соответствовать таковым в application.properties, сейчас они разные

**Comment by MironovED** [comment]
Вопрос решен
